### ISSUE TITLE
Different Date/Time formats used in the API

### ISSUE THREAD

**Issue by chluehr** [Forecast-it/API#16]
Date/Time information uses different formats in the query parameters vs the data.

Example:

- created_at: gives 2017-01-14T18:46:56Z
- but GET /cards?updated_after=DDMMYYYYTHHmmss

Suggestion: Use a single, consistent Date/Time Format for data and query parameters.

**Comment by danny-larsen** [comment]
This was a decision we took to make it easier to query for data and easier to read the data from from code.
