### ISSUE TITLE
Client GET ... PUT: Country is not allowed to be empty

### ISSUE THREAD

**Issue by chluehr** [Forecast-it/API#18]
When retrieving a Client with just a name via GET and then updating it via PUT results in an error, that the country field can not be empty. This looks like an inconsistency.

Client error: `PUT https://api.forecast.it/api/v1/clients/15456` resulted in a `400 Bad Request` response:
  {"status":400,"message":"\"country\" is not allowed to be empty"}

Furthermore, via GET, the country (even if it set via the Forecast UI) is not returned! Explicitly setting country to, e.g.  "Germany" works, though.

**Comment by tilds** [comment]
Hi chluehr, thank you for letting us know about this. We will get this fixed as soon as possible.

**Comment by christophluehr** [comment]
.. seems it needs "DE" instead of "Germany" since today ;-)

(is there any kind of API versioning planned? or at least some kind of "changes" channel i can read in order to prevent my integration from breaking?)

**Comment by danny-larsen** [comment]
Hi,

We do have versioning but reserve these for actual breaking changes. We do not currently have a "changes" channel. This is a good idea I will take up with the team.
