### ISSUE TITLE
Get Projects connected to Person

### ISSUE THREAD

**Issue by athaeryn** [Forecast-it/API#24]
Hi! I'm trying to build a few simple visualizations on top of this API, and I need to get projects for a specific user. I'd expect something like `/persons/:id/projects`, but don't see it in the docs. Is there a route that I could use to get this information? Currently I have to piece it together from a couple other responses.

Thanks!

**Comment by danny-larsen** [comment]
Currently there is no direct route for that. I will see what can be done.

**Comment by danny-larsen** [comment]
This is available now. Check out the docs here: https://github.com/Forecast-it/API/blob/master/sections/persons.md#get-person-projects
