### ISSUE TITLE
Add field to Project for allocation mode

### ISSUE THREAD

**Issue by athaeryn** [Forecast-it/API#25]
I've _almost_ been able to recreate the utilization numbers on the scheduling view for some internal dashboards/reports, but I've run into some issues with data consistency. For projects that were using project allocations but have switched to task allocations, there are still project allocations being returned by the API (and vice versa). Unfortunately, there's no way I can find to determine which type of allocations should be used for a given project. Could the value of this toggle be added to the API so I can ignore the irrelevant allocations?

![image](https://user-images.githubusercontent.com/1226972/57389756-7be70100-7180-11e9-89f1-3ef1bd811651.png)

Thanks!

**Comment by danny-larsen** [comment]
Hi,
We will add this information to the project endpoint.

**Comment by danny-larsen** [comment]
This is now in the projects. Called "use_project_allocations".

**Comment by athaeryn** [comment]
Thanks!
