### ISSUE TITLE
PUT endpoint returns 500 when used on deleted card

### ISSUE THREAD

**Issue by AndreLachance** [Forecast-it/API#26]
# 500 HTTP Response when calling **PUT** on a deleted card

## Current behaviour:

Calling the api with PUT @ https://api.forecast.it/api/v1/cards/1 returns 500 if the card ID belongs to a previously existing card that was deleted via the user interface.

## Expected behaviour:

404 Not found
or
201 Created

Thank you for taking the time to look at this. This is currently causing us quite a headache for the development of our internal syncing tool.

**Comment by danny-larsen** [comment]
Thanks for reporting. This will be fixed in the next deployment.
